name: Biên dịch Game (IL2CPP scripting backend)
on: workflow_dispatch
jobs:
  build-Unity-Windows:
    name: Biên dịch StandaloneWindows trên máy chủ Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows 
          - StandaloneWindows64
    permissions:
      actions: write
    steps:
      - name: Clone pk9r327/Dragonboy branch Unity-project
        uses: actions/checkout@v4.1.1
        with:
          repository: pk9r327/Dragonboy
          ref: Unity-project
      - name: Cache
        id: cache-restore
        uses: actions/cache@v4.0.2
        with:
          path: GameProject/DragonBoy/Library
          key: Library-Windows
      - name: Tải artifact Build-${{ matrix.targetPlatform }}-IL2CPP
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_search: false
          workflow_conclusion: success
          if_no_artifact_found: warn
          allow_forks: false
          name: Build-${{ matrix.targetPlatform }}-IL2CPP
          path: build/${{ matrix.targetPlatform }}
      - name: Đổi scripting backend thành IL2CPP
        run: cd GameProject && pwsh ./set_scripting_backend.ps1 -projectSettingsPath "DragonBoy/ProjectSettings/ProjectSettings.asset" -platform ${{ matrix.targetPlatform }} -scriptingBackend IL2CPP || powershell ./set_scripting_backend.ps1 -projectSettingsPath "DragonBoy/ProjectSettings/ProjectSettings.asset" -platform ${{ matrix.targetPlatform }} -scriptingBackend IL2CPP;     
      - name: Biên dịch dự án
        uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: GameProject/DragonBoy
          buildName: DragonBoy CommunityMod
          allowDirtyBuild: true
          versioning: Custom
          version: 0.0.1
      - name: Upload file game đã biên dịch
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Build-${{ matrix.targetPlatform }}-IL2CPP
          path: build/${{ matrix.targetPlatform }}
      - name: Xóa cache trước đó
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh cache delete "Library-Windows" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lưu cache
        uses: actions/cache/save@v4.0.2
        with: 
          path: GameProject/DragonBoy/Library
          key: Library-Windows
  build-Unity-Linux:
    name: Biên dịch StandaloneLinux64 trên máy chủ Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      actions: write
    steps: 
      - name: Clone pk9r327/Dragonboy branch Unity-project
        uses: actions/checkout@v4.1.1
        with:
          repository: pk9r327/Dragonboy
          ref: Unity-project
      - name: Cache
        uses: actions/cache@v4.0.2
        id: cache-restore
        with:
          path: GameProject/DragonBoy/Library
          key: Library-Linux
      - name: Tải artifact Build-StandaloneLinux64-IL2CPP
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_search: false
          workflow_conclusion: success
          if_no_artifact_found: warn
          allow_forks: false
          name: Build-StandaloneLinux64-IL2CPP
          path: build/StandaloneLinux64
      - name: Đổi scripting backend thành IL2CPP
        run: cd GameProject && chmod +x set_scripting_backend.sh && ./set_scripting_backend.sh "DragonBoy/ProjectSettings/ProjectSettings.asset" "StandaloneLinux64" "IL2CPP"
      - name: Giải phóng bộ nhớ
        uses: jlumbroso/free-disk-space@v1.3.1
      - name: Biên dịch dự án
        uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64
          projectPath: GameProject/DragonBoy
          buildName: DragonBoy CommunityMod
          allowDirtyBuild: true
          versioning: Custom
          version: 0.0.1
      - name: Upload file game đã biên dịch
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Build-StandaloneLinux64-IL2CPP
          path: build/StandaloneLinux64
      - name: Xóa cache trước đó
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh cache delete "Library-Linux" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lưu cache
        uses: actions/cache/save@v4.0.2
        with: 
          path: GameProject/DragonBoy/Library
          key: Library-Linux
  build-Unity-Android:
    name: Biên dịch Android trên máy chủ Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      actions: write
    steps: 
      - name: Clone pk9r327/Dragonboy branch Unity-project
        uses: actions/checkout@v4.1.1
        with:
          repository: pk9r327/Dragonboy
          ref: Unity-project
      - name: Cache
        uses: actions/cache@v4.0.2
        id: cache-restore
        with:
          path: GameProject/DragonBoy/Library
          key: Library-Android-IL2CPP
      - name: Tải artifact Build-Android-IL2CPP
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_search: false
          workflow_conclusion: success
          if_no_artifact_found: warn
          allow_forks: false
          name: Build-Android-IL2CPP
          path: build/Android
      - name: Đổi scripting backend thành IL2CPP
        run: cd GameProject && chmod +x set_scripting_backend.sh && ./set_scripting_backend.sh "DragonBoy/ProjectSettings/ProjectSettings.asset" "Android" "IL2CPP"
      - name: Giải phóng bộ nhớ (Android build)
        uses: jlumbroso/free-disk-space@v1.3.1
      - name: Biên dịch dự án
        uses: game-ci/unity-builder@v4.2.3
        # continue-on-error: true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          androidKeystoreName: DragonBoy-pk9r327-UnityProject.keystore # This file won't exist, but this property needs to exist.
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          androidTargetSdkVersion: AndroidApiLevel29
          projectPath: GameProject/DragonBoy
          buildName: DragonBoy CommunityMod
          allowDirtyBuild: true
          versioning: Custom
          version: 0.0.1
      - name: Upload file game đã biên dịch
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Build-Android-IL2CPP
          path: build/Android
      - name: Xóa cache trước đó
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh cache delete "Library-Android-IL2CPP" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lưu cache
        uses: actions/cache/save@v4.0.2
        with: 
          path: GameProject/DragonBoy/Library
          key: Library-Android-IL2CPP    