name: Test
on: workflow_dispatch
jobs:
  Test:
    name: Test
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Clone pk9r327/Dragonboy branch Unity-project
        uses: actions/checkout@v4.1.1
        with:
          repository: pk9r327/Dragonboy
          ref: Unity-project
      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: latest-commit.txt
          key: latest-commit-${{ hashFiles('latest-commit.txt') }}
          restore-keys: latest-commit-
      - run: git rev-parse HEAD
      # - run: cat latest-commit.txt
      - run: git rev-parse HEAD > latest-commit.txt
      - run: cat latest-commit.txt
      - name: Lưu cache
        uses: actions/cache/save@v4.0.2
        with: 
          path: latest-commit.txt
          key: latest-commit-${{ hashFiles('latest-commit.txt') }}