name: Phát hành artiact mới nhất
on: workflow_dispatch
jobs:
  release-latest-artifacts:
    name: Phát hành artiact mới nhất
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Tải artifact mới nhất
        uses: dawidd6/action-download-artifact@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success
          if_no_artifact_found: warn
          allow_forks: false
          skip_unpack: true
          path: build
      - name: Lấy danh sách artifact
        run: |
          echo 'artifacts<<EOF' >> $GITHUB_ENV
          cd build
          ls -1 | xargs realpath
          ls -1 | xargs realpath >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Phát hành artifact
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.artifacts }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Latest build
          draft: false
          prerelease: false
          tag_name: latest
      - run: |
          echo ${{ steps.release.outputs.url }}
          echo ${{ steps.release.outputs.id }}
          echo ${{ steps.release.outputs.upload_url }}
          echo ${{ steps.release.outputs.assets }}