name: Test
on: 
  workflow_dispatch:
    inputs:
      test1:
        description: 'Test 1'
        required: true
        type: environment
      test2:
        description: 'Test 2'
        required: true
        type: string
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
