name: Test
on: workflow_dispatch
jobs:
  build-Unity-Windows:
    name: Biên dịch StandaloneWindows trên máy chủ Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneWindowsArm64
        scriptingBackend:
          - Mono2x 
          - IL2CPP
    permissions:
      actions: write
    steps:
      - name: Clone pk9r327/Dragonboy branch Unity-project-v2023
        uses: actions/checkout@v4.1.1
        with:
          repository: pk9r327/Dragonboy
          ref: Unity-project-v2023
      - name: Cache
        id: cache-restore
        uses: actions/cache@v4.0.2
        with:
          path: GameProject/DragonBoy/Library
          key: Library-Windows   
      - name: Biên dịch dự án
        if: ${{ matrix.targetPlatform != 'StandaloneWindowsArm64' }}
        uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: GameProject/DragonBoy
          buildName: DragonBoy CommunityMod
          versioning: Custom
          version: 0.0.1
          buildMethod: UnityBuilderAction.BuildScript.Build
          customParameters: -scriptingBackend ${{ matrix.scriptingBackend }}
      - name: Biên dịch dự án (Arm64)
        if: ${{ matrix.targetPlatform == 'StandaloneWindowsArm64' }}
        uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: GameProject/DragonBoy
          buildName: DragonBoy CommunityMod
          versioning: Custom
          version: 0.0.1
          buildMethod: UnityBuilderAction.BuildScript.Build
          customParameters: -scriptingBackend ${{ matrix.scriptingBackend }} -architecture ARM64
      - name: Upload file game đã biên dịch
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Build-${{ matrix.targetPlatform }}-${{ matrix.scriptingBackend }}
          path: build/${{ matrix.targetPlatform }}
      - name: Xóa cache trước đó
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh cache delete "Library-Windows" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lưu cache
        uses: actions/cache/save@v4.0.2
        with: 
          path: GameProject/DragonBoy/Library
          key: Library-Windows