name: Test
on: workflow_dispatch
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - run: |
          {
            buildAccountManager="success"
            buildUnityLinux="success"
            buildUnityWindows="success"
            buildUnityAndroid="failure"
            failure_count=0
            if [ "$buildAccountManager" == "failure" ]; then
              ((failure_count++))
            fi
            if [ "$buildUnityLinux" == "failure" ]; then
              ((failure_count++))
            fi
            if [ "$buildUnityWindows" == "failure" ]; then
              ((failure_count++))
            fi
            if [ "$buildUnityAndroid" == "failure" ]; then
              ((failure_count++))
            fi
            echo -n "color="
            if [ "$failure_count" -eq 4 ]; then
              echo "0xff0000"
            elif [ "$failure_count" -eq 3 ]; then
              echo "0xff5a00"
            elif [ "$failure_count" -eq 2 ]; then
              echo "0xffa500"
            elif [ "$failure_count" -eq 1 ]; then
              echo "0xffff00"
            else
              echo "0x00ff00"
            fi
          } >> "$GITHUB_ENV"